### ISSUE TITLE
mozmail.com is in both allowDomains.txt and denyDomains.txt, should be removed from denyDomains.txt

### ISSUE THREAD

**Issue by jwhitlock** [amieiro/disposable-email-domains#14]
`mozmail.com` appears in `allowDomains.txt`:

https://github.com/amieiro/disposable-email-domains/blob/172b06ff42fe3bf23c2b63381cb02979eaaf3aeb/allowDomains.txt#L335

and in `denyDomains.txt` (around line 95160, preview may be busted):

https://github.com/amieiro/disposable-email-domains/blob/172b06ff42fe3bf23c2b63381cb02979eaaf3aeb/denyDomains.txt#L95160

I'm a developer for [Firefox Relay](https://relay.firefox.com/). I'd like `mozmail.com` to be in the `allowDomains.txt` and not in `denyDomains.txt`, as well as the JSON variants.

Back in 2021, we took over the mozmail.com domain for our aliases. We are operating Relay with a number of features that I think mitigate the risks that these aliases pose:

* Bounces & deliver-ability - if our user disables an @mozmail.com alias, we DO NOT trigger a bounce. Instead, [we silently drop the email](https://github.com/mozilla/fx-private-relay/blob/4ccc3957076b37d9b263241e0bd727f41893ac15/emails/views.py#L406-L422).
* Anti-abuse protections - we limit our free users to 5 total aliases, and we rate-limit our premium customers so they cannot create large-scale throw-away aliases for abusive sign-ups and behaviors.

I've found `mozmail.com` in at least one of the source lists and I'm working to remove it there (https://github.com/kslr/disposable-email-domains/issues/56). I'd appreciate if it was removed from `denyDomains.txt` here as well, in case an upstream list is not responsive.

**Comment by jwhitlock** [comment]
`mozmail.com` has been removed from `kslr/disposable-email-domains`, after _its_ upstream provider was updated. Hopefully `mozmail.com` will also be removed after the next auto-update.

**Comment by amieiro** [comment]
Hi @jwhitlock. Thank you for your feedback. 
The idea behind the `allowDomains` file is to stop checking in the `denyDomains` list if the program founds a domain in this list, to avoid false positives, like this situation. This `allowDomains` list is maintained by hand, but the `denyDomains` list is maintained automatically by a script, so if one of the [sources](https://github.com/amieiro/disposable-email-domains/blob/0ff90f9970f558bbf1ff9cc48d457e4c9293c154/creator/app/Console/Commands/CreateDisposableEmailDomainsFilesCommand.php#L12-L28) I use to create this list has one domain in her `denyDomain` list, I am going to add to my list. I have found the mozmail.com domain in [this upstream list](https://github.com/micke/valid_email2/blob/bd01c20900941de4e018a98a692f6ec5e64cacbb/config/disposable_email_domains.txt), so, please, try to remove from this list and the changes will automatically be added to mine.

**Comment by jwhitlock** [comment]
Thanks, that's what I suspected. I've opened https://github.com/micke/valid_email2/issues/202 and a related PR. It looks like the maintainer makes monthly updates, so I hope it will be removed soon.

I could also see a change in `CreateDisposableEmailDomainsFilesCommand.php` to:

1. Load the allow lists first
2. Load the deny lists
3. Remove any deny domains in the allowed domains

Would you be interested in that PR?

**Comment by amieiro** [comment]
I think the approach should be the opposite:
1. Load the deny list.
2. Remove from the deny list all the domains in the allow list.
3. Save this updated deny list in the file.

If this approach is ok to you, I will try to do it soon.

**Comment by jwhitlock** [comment]
That works for me, especially the part where you do the work 😀 

At first, I thought you were proposing that a domain in the deny list removes it from the allow list. That would be bad for me, since my domain `mozmail.com` would then be out of the allow list, but it is a reasonable policy for the project. I'd continue to work to get `mozmail.com` off all the deny lists I can, so eventually it would be off your deny list and only on the allow list.

Now I'm thinking of policies, since the README doesn't say how the lists are used. I guess a website or mailing list owner would want one of these policies, from looser to stricter:

1. **Allow All** - Allow all addresses (does not use the project)
2. **Deny unknown** - Deny addresses not tracked in either list
3. **Deny** - Deny addresses when the domain is in the deny list but not the allow list
4. **Strict Deny** - Deny addresses when the domain is in the deny list
5. **Allow** - Allow addresses when the domain is in the allow list
6. **Strict Allow** - Allow addresses when the domain is in the allow list and not in the deny list

I could see different names (for example, "Deny unknown" could be "Allow known"), but it makes it easier to talk about what changes for the users.

I'm doubtful many sites are using both lists to implement the **Deny** and **Strict Allow** strategies. You may have different information. I thought it might be a bug, so I opened this ticket.

If you make this change, then you're switching the **Deny** websites to **Strict Deny**, and the **Strict Allow* sites to **Allow**, and removing the data they would need to implement their preferred strategy.  I think this hurts the **Strict Allow** sites more than the **Deny** sites, since I imagine sites are using these lists to exclude bad actors.

If you created a `bothList.txt` and `bothList.json` with entries that appeared on both lists, then the **Strict Allow** sites could still implement their strategies with some code changes. You could create the `bothList.txt` and `bothList.json` without removing from either `allowList` or `denyList` - it is the same information, but a shorter list to check for maybes. Or, maybe the best thing is to update the README to inform that domains could appear on both lists, so users could make more informed decisions.

I made an exhaustive table, to see if I'm missing any rational strategies:

| |In Allow<br>Not in Deny<br>"Not Disposable"|In Allow<br>In Deny<br>"Maybe Disposable"|Not in Allow<br>In Deny<br>"Disposable"|Not in Allow<br>Not in Deny<br>"Unknown"|
|-:|:-:|:-:|:-:|:-:|
|**Allow All**|Allow|Allow|Allow|Allow|
|**Deny unknown**|Allow|Allow|Allow|Deny|
|**Deny**|Allow|Allow| Deny|Allow|
|**Allow**|Allow|Allow| Deny| Deny|
|*Deny maybes*|Allow| Deny|Allow|Allow|
|*Deny maybes, unknowns*|Allow| Deny|Allow| Deny|
|**Strict Deny**|Allow| Deny| Deny|Allow|
|**Strict Allow**|Allow| Deny| Deny| Deny|
|*Block allowed*| Deny|Allow|Allow|Allow|
|*Only maybes, disposable*| Deny|Allow|Allow| Deny|
|*Only maybes, unknowns*| Deny|Allow| Deny|Allow|
|*Only maybes*| Deny|Allow| Deny| Deny|
|*Block allowed, maybes*| Deny| Deny|Allow|Allow|
|*Only disposable*| Deny| Deny|Allow| Deny|
|*Only unknown*| Deny| Deny| Deny|Allow|
|*Block All*| Deny| Deny| Deny| Deny|

In either case, I imagine I did more work writing this comment than it will take to change the code :sweat:

**Comment by jwhitlock** [comment]
`mozmail.com` was removed from https://github.com/micke/valid_email2, and this repo picked up the change and removed it from `denyDomains.txt`.

I'll leave up #17 to fix the double-entry, if desired.
