### ISSUE TITLE
duck.com incorrectly listed as a disposable email service

### ISSUE THREAD

**Issue by astroblaster** [amieiro/disposable-email-domains#19]
Hello,

I'm writing as a postmaster for duck.com, DuckDuckGo's email forwarding service.

It seems we've landed on your list as a disposable email. We don't intend for our service to be used as a disposable email. We take any reports of abuse seriously. Would you consider removing this entry?

Thank you,

Brian Kowalewicz

**Comment by amieiro** [comment]
Hi @astroblaster 

Thank you for your feedback. The duck.com domain has been added to our `secureDomains.txt` file [here](https://github.com/amieiro/disposable-email-domains/commit/1c453cfcaf2a1a37747555fb830284ca67a2ba2f), so it should not appear in the future in the `denyDomains` files. 

Thank you
