### ISSUE TITLE
wildcards in the domains

### ISSUE THREAD

**Issue by noe** [amieiro/disposable-email-domains#22]
At the beginning of the `denyDomains` list, there are some wildcards:

```
*.cfo2go.ro
*.istii.ro
*.onlysext.com
*.spamtrap.ro
*.uu.gl
*.wupics.com
```
Shouldn't the list be just the domain part without the subdomain?

Thanks.

**Comment by amieiro** [comment]
Done [here](https://github.com/amieiro/disposable-email-domains/commit/4df6400133ddbf054a0755ee783012164fe8f1a4). Thank you for the feedback.
