### ISSUE TITLE
Description of what is in each list and how they should be used

### ISSUE THREAD

**Issue by noe** [amieiro/disposable-email-domains#23]
There are 3 domain lists in the repository: `denyDomains`, `allowDomains` and `secureDomains`. It is not clear what they contain (e.g. what is the difference between `allowDomains` and `secureDomains`?) and how they should be used.

Would it be possible to add to the readme file:

1. Descriptions of the contents of each list.
2. Description of the logic to apply them, e.g. "step 1: If the domain is in the allowDomains list, the email is not disposable; step 2: if the domain is in the denyDomains list, it is disposable, ...".

Thank you, and thank you for this repo, it's very useful and complete.

**Comment by amieiro** [comment]
Added [here](https://github.com/amieiro/disposable-email-domains/commit/948ca7e9f21f4f41d80907ec3f99b8396bc54c7f) and [here](https://github.com/amieiro/disposable-email-domains/commit/6608af1db690d7dbcfb3fd1ff392e8bc1ff0966e).
